default:
  image: node:18
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

# stages
stages:
  - build
  - test
  - deploy

# tasks == every task is part of stage
install_dependencies:
  stage: build
  script:
    - yarn

build_job:
  stage: build
  script:
    - yarn build
  variables:
    PUBLIC_URL: https://ya.coder.gitlab.io/react-course
    PUBLIC_PATH: /react-course
  needs:
    - install_dependencies
  artifacts:
    paths:
      - dist/

test_job:
  stage: test
  script:
    - yarn test:ci
  needs:
    - install_dependencies 
  artifacts:
    reports:
      junit: junit.xml

# reserver task's name
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist public
  artifacts:
    paths:
      - public
